# Created by Ivan at 29.01.2023
Feature: Merge
  Combining n-level houses with n-1 level houses


  @positive
  Scenario: Simple merge-1
    Given Game board with default preset houses "initial_board"
    Then User have in board queue "[1,1,1,1]"
    When User place on "user_place"
    Then A new "result_board" will be generated by user with the result of the merging 3 house lvl 1 into 1 house lvl 2

  @negative
  Scenario: Simple merge-2
    # Negative test to check the impossibility of merging houses in different parts of the game board
    Given Game board with default preset houses "initial_board"
    Then User have in board queue "[1,1,1,1]"
    When User place on "user_place"
    Then A new "result_board" should not be generated by user as the result of the merging

  @negative
  Scenario: Simple merge-3
    # Negative test to check the impossibility of merging houses of different lvl
    Given Game board with default preset houses "initial_board"
    Then User have in board queue "[1,1,1,1]"
    When User place on "user_place"
    Then A new "result_board" should not be generated by user as the result of the merging
