# Created by Ivan at 29.01.2023
Feature: Merge
  Combining n-level houses with n-1 level houses


  @positive
  Scenario: Simple merge-1
    Given Game board with default preset houses fixtures/positive/default.yml
    Then User have in board queue [1,1,1,1]
    When User place on fixtures/positive/user_place.yml
    Then A new fixtures/positive/result_board.yml will be generated by user with the result of the merging

  @negative
  Scenario: Negative test to check the impossibility of merging houses in different parts of the game board
    Given Game board with default preset houses fixtures/negative/first/default.yml
    Then User have in board queue [1,1,1,1]
    When User place on fixtures/negative/first/user_place.yml
    Then A new fixtures/negative/first/result_board.yml should not be generated by user as the result of the merging


  @negative
  Scenario: Negative test to check the impossibility of merging houses of different lvl
    Given Game board with default preset houses fixtures/negative/second/default.yml
    Then User have in board queue [1,1,1,3]
    When User place on fixtures/negative/second/user_place.yml
    Then A new fixtures/negative/second/result_board.yml should not be generated by user as the result of the merging
