# content of test_merge_2.py
# Negative test

import json

from pytest_bdd import scenario, given, then, when, parsers

from tests.models.board import Board


@scenario('merge.feature', 'Simple merge-2')
def test_merge_houses_negative():
    """"""
    pass


EXTRA_TYPES = {
    'String': str,
    "List": list
}

CONVERTERS = {
    'initial_board': str,
    "result_board": str,
    "user_queue": list,
    "changed_board": str,
    "user_place": str
}

with open('fixtures/negative/simple_merge-2.json') as file:
    json_data = json.loads(file.read())


@given(parsers.cfparse('Game board with default preset houses "{initial_board:String}"', extra_types=EXTRA_TYPES),
       target_fixture='game_board')
@given('Game board with default preset houses "initial_board"', target_fixture='game_board')
def game_in_progress(initial_board):
    board = Board()
    initial_board = json_data.get('initial_board')
    board.create_custom_board(initial_board)
    return {"initial_board": initial_board, "board": board}


@then(parsers.cfparse('User have in board queue "{user_queue:List}"', extra_types=EXTRA_TYPES),
      target_fixture='user_queue')
@then('User have in board queue "<user_queue>"')
def user_queue(user_queue):
    return {'user_queue': user_queue}


@when(parsers.cfparse('User place on "{user_place:String}"', extra_types=EXTRA_TYPES), target_fixture="change_board")
@when('User place on "<user_place>"')
def change_board(game_board, user_place):
    user_place = json_data.get(user_place)
    x, y = user_place
    board = game_board.get('initial_board')
    board[x][y] = 1
    return user_place


@then(parsers.cfparse(
    'A new "{result_board:String}" should not be generated by user as the result of the merging',
    extra_types=EXTRA_TYPES))
@then(
    'A new "<result_board>" should not be generated by user as the result of the merging')
def merge_house(change_board, game_board, result_board):
    number_of_houses_before = 0
    result_board = json_data.get(result_board)
    board = game_board.get('board')
    for i in board.get_board():
        for j in i:
            if j != 0:
                number_of_houses_before = number_of_houses_before + 1
    current_number_of_houses = 0
    for i in result_board:
        for j in i:
            if j != 0:
                current_number_of_houses = current_number_of_houses + 1

    assert board.get_board() == result_board
    assert current_number_of_houses == number_of_houses_before
