# Created by User at 1.02.2023
Feature: Board
  Checking the installation of elements from the queue to the board


  @positive
  Scenario: User puts the house at empty cell
    Given Game board with default preset houses tests/fixtures/boards/give/simple_board/positive/default.yml
    Given User have in board queue [1,1,1,1]
    When User place on [3,1]
    Then A new tests/fixtures/boards/then/simple_board/positive/result_board.yml should  be generated by user as a result of the installation of the house at empty cell

  @positive
  Scenario: User puts the house at used cell
    Given Game board with default preset houses tests/fixtures/boards/give/simple_board/negative/default.yml
    Given User have in board queue [1,1,1,1]
    When User place on [4,1]
    Then Nothing will happen

  @positive
  Scenario: Checking the end of the game after the entire game board is full
    Given Fully filled board with houses of different levels
    Then Game is stopped

  @negative
  Scenario: The user is trying to change the position of the already placed house
    Given Given Random numbers of houses on the game table
    When The user tries to drag the house to another position
    Then Nothing will happen


  @negative
  Scenario: The user is trying to place the house that does not exists in queue
    Given Given Random numbers of houses on the game table
    Given User have in board queue [1,1,1,1]
    Given House that does not exists in queue
    When User try to place a house on random empty place
    Then Nothing will happen
